/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as EnterRouteImport } from './routes/enter'
import { Route as FindsRouteImport } from './routes/finds'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as StewardRouteImport } from './routes/steward'
import { Route as ApiReportRouteImport } from './routes/api/report'
import { Route as ApiSponsorRouteImport } from './routes/api/sponsor'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiForgeArchiveRouteImport } from './routes/api/forge/archive'
import { Route as ApiForgeChallengeRouteImport } from './routes/api/forge/challenge'
import { Route as ApiForgeFindsRouteImport } from './routes/api/forge/finds'
import { Route as ApiForgeSavesRouteImport } from './routes/api/forge/saves'
import { Route as ApiForgeSessionRouteImport } from './routes/api/forge/session'
import { Route as ApiForgeStewardRouteImport } from './routes/api/forge/steward'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterRoute = EnterRouteImport.update({
  id: '/enter',
  path: '/enter',
  getParentRoute: () => rootRouteImport,
} as any)
const FindsRoute = FindsRouteImport.update({
  id: '/finds',
  path: '/finds',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const StewardRoute = StewardRouteImport.update({
  id: '/steward',
  path: '/steward',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportRoute = ApiReportRouteImport.update({
  id: '/api/report',
  path: '/api/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSponsorRoute = ApiSponsorRouteImport.update({
  id: '/api/sponsor',
  path: '/api/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForgeArchiveRoute = ApiForgeArchiveRouteImport.update({
  id: '/api/forge/archive',
  path: '/api/forge/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForgeChallengeRoute = ApiForgeChallengeRouteImport.update({
  id: '/api/forge/challenge',
  path: '/api/forge/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForgeFindsRoute = ApiForgeFindsRouteImport.update({
  id: '/api/forge/finds',
  path: '/api/forge/finds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForgeSavesRoute = ApiForgeSavesRouteImport.update({
  id: '/api/forge/saves',
  path: '/api/forge/saves',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForgeSessionRoute = ApiForgeSessionRouteImport.update({
  id: '/api/forge/session',
  path: '/api/forge/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForgeStewardRoute = ApiForgeStewardRouteImport.update({
  id: '/api/forge/steward',
  path: '/api/forge/steward',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/archive': typeof ArchiveRoute
  '/enter': typeof EnterRoute
  '/finds': typeof FindsRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/steward': typeof StewardRoute
  '/api/report': typeof ApiReportRoute
  '/api/sponsor': typeof ApiSponsorRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/forge/archive': typeof ApiForgeArchiveRoute
  '/api/forge/challenge': typeof ApiForgeChallengeRoute
  '/api/forge/finds': typeof ApiForgeFindsRoute
  '/api/forge/saves': typeof ApiForgeSavesRoute
  '/api/forge/session': typeof ApiForgeSessionRoute
  '/api/forge/steward': typeof ApiForgeStewardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/archive': typeof ArchiveRoute
  '/enter': typeof EnterRoute
  '/finds': typeof FindsRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/steward': typeof StewardRoute
  '/api/report': typeof ApiReportRoute
  '/api/sponsor': typeof ApiSponsorRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/forge/archive': typeof ApiForgeArchiveRoute
  '/api/forge/challenge': typeof ApiForgeChallengeRoute
  '/api/forge/finds': typeof ApiForgeFindsRoute
  '/api/forge/saves': typeof ApiForgeSavesRoute
  '/api/forge/session': typeof ApiForgeSessionRoute
  '/api/forge/steward': typeof ApiForgeStewardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/archive': typeof ArchiveRoute
  '/enter': typeof EnterRoute
  '/finds': typeof FindsRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/steward': typeof StewardRoute
  '/api/report': typeof ApiReportRoute
  '/api/sponsor': typeof ApiSponsorRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/forge/archive': typeof ApiForgeArchiveRoute
  '/api/forge/challenge': typeof ApiForgeChallengeRoute
  '/api/forge/finds': typeof ApiForgeFindsRoute
  '/api/forge/saves': typeof ApiForgeSavesRoute
  '/api/forge/session': typeof ApiForgeSessionRoute
  '/api/forge/steward': typeof ApiForgeStewardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/archive'
    | '/enter'
    | '/finds'
    | '/login'
    | '/saved'
    | '/steward'
    | '/api/report'
    | '/api/sponsor'
    | '/api/stats'
    | '/api/auth/$'
    | '/api/forge/archive'
    | '/api/forge/challenge'
    | '/api/forge/finds'
    | '/api/forge/saves'
    | '/api/forge/session'
    | '/api/forge/steward'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/archive'
    | '/enter'
    | '/finds'
    | '/login'
    | '/saved'
    | '/steward'
    | '/api/report'
    | '/api/sponsor'
    | '/api/stats'
    | '/api/auth/$'
    | '/api/forge/archive'
    | '/api/forge/challenge'
    | '/api/forge/finds'
    | '/api/forge/saves'
    | '/api/forge/session'
    | '/api/forge/steward'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/archive'
    | '/enter'
    | '/finds'
    | '/login'
    | '/saved'
    | '/steward'
    | '/api/report'
    | '/api/sponsor'
    | '/api/stats'
    | '/api/auth/$'
    | '/api/forge/archive'
    | '/api/forge/challenge'
    | '/api/forge/finds'
    | '/api/forge/saves'
    | '/api/forge/session'
    | '/api/forge/steward'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ArchiveRoute: typeof ArchiveRoute
  EnterRoute: typeof EnterRoute
  FindsRoute: typeof FindsRoute
  LoginRoute: typeof LoginRoute
  SavedRoute: typeof SavedRoute
  StewardRoute: typeof StewardRoute
  ApiReportRoute: typeof ApiReportRoute
  ApiSponsorRoute: typeof ApiSponsorRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiForgeArchiveRoute: typeof ApiForgeArchiveRoute
  ApiForgeChallengeRoute: typeof ApiForgeChallengeRoute
  ApiForgeFindsRoute: typeof ApiForgeFindsRoute
  ApiForgeSavesRoute: typeof ApiForgeSavesRoute
  ApiForgeSessionRoute: typeof ApiForgeSessionRoute
  ApiForgeStewardRoute: typeof ApiForgeStewardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter': {
      id: '/enter'
      path: '/enter'
      fullPath: '/enter'
      preLoaderRoute: typeof EnterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finds': {
      id: '/finds'
      path: '/finds'
      fullPath: '/finds'
      preLoaderRoute: typeof FindsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steward': {
      id: '/steward'
      path: '/steward'
      fullPath: '/steward'
      preLoaderRoute: typeof StewardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report': {
      id: '/api/report'
      path: '/api/report'
      fullPath: '/api/report'
      preLoaderRoute: typeof ApiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sponsor': {
      id: '/api/sponsor'
      path: '/api/sponsor'
      fullPath: '/api/sponsor'
      preLoaderRoute: typeof ApiSponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forge/archive': {
      id: '/api/forge/archive'
      path: '/api/forge/archive'
      fullPath: '/api/forge/archive'
      preLoaderRoute: typeof ApiForgeArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forge/challenge': {
      id: '/api/forge/challenge'
      path: '/api/forge/challenge'
      fullPath: '/api/forge/challenge'
      preLoaderRoute: typeof ApiForgeChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forge/finds': {
      id: '/api/forge/finds'
      path: '/api/forge/finds'
      fullPath: '/api/forge/finds'
      preLoaderRoute: typeof ApiForgeFindsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forge/saves': {
      id: '/api/forge/saves'
      path: '/api/forge/saves'
      fullPath: '/api/forge/saves'
      preLoaderRoute: typeof ApiForgeSavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forge/session': {
      id: '/api/forge/session'
      path: '/api/forge/session'
      fullPath: '/api/forge/session'
      preLoaderRoute: typeof ApiForgeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forge/steward': {
      id: '/api/forge/steward'
      path: '/api/forge/steward'
      fullPath: '/api/forge/steward'
      preLoaderRoute: typeof ApiForgeStewardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ArchiveRoute: ArchiveRoute,
  EnterRoute: EnterRoute,
  FindsRoute: FindsRoute,
  LoginRoute: LoginRoute,
  SavedRoute: SavedRoute,
  StewardRoute: StewardRoute,
  ApiReportRoute: ApiReportRoute,
  ApiSponsorRoute: ApiSponsorRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiForgeArchiveRoute: ApiForgeArchiveRoute,
  ApiForgeChallengeRoute: ApiForgeChallengeRoute,
  ApiForgeFindsRoute: ApiForgeFindsRoute,
  ApiForgeSavesRoute: ApiForgeSavesRoute,
  ApiForgeSessionRoute: ApiForgeSessionRoute,
  ApiForgeStewardRoute: ApiForgeStewardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
